
ThisBuild / organization := "com.niclas"
ThisBuild / scalaVersion := "2.13.3"

lazy val commonSettings = Seq(
	fork := true
)


lazy val day01 = (project in file("Day 1"))
	.settings(commonSettings)
lazy val day02 = (project in file("Day 2"))
	.settings(commonSettings)
lazy val day03 = (project in file("Day 3"))
	.settings(commonSettings)
lazy val day04 = (project in file("Day 4"))
	.settings(commonSettings)
lazy val day05 = (project in file("Day 5"))
	.settings(commonSettings)
lazy val day06 = (project in file("Day 6"))
	.settings(commonSettings)
lazy val day07 = (project in file("Day 7"))
	.settings(commonSettings)
lazy val day08 = (project in file("Day 8"))
	.settings(commonSettings)
lazy val day09 = (project in file("Day 9"))
	.settings(commonSettings)
lazy val day10 = (project in file("Day 10"))
	.settings(commonSettings)
lazy val day11 = (project in file("Day 11"))
	.settings(commonSettings)
lazy val day12 = (project in file("Day 12"))
	.settings(commonSettings)
lazy val day13 = (project in file("Day 13"))
	.settings(commonSettings)
lazy val day14 = (project in file("Day 14"))
	.settings(commonSettings)
lazy val day15 = (project in file("Day 15"))
	.settings(commonSettings)
lazy val day16 = (project in file("Day 16"))
	.settings(commonSettings)
lazy val day17 = (project in file("Day 17"))
	.settings(commonSettings)
lazy val day18 = (project in file("Day 18"))
	.settings(commonSettings)
lazy val day19 = (project in file("Day 19"))
	.settings(commonSettings)
lazy val day20 = (project in file("Day 20"))
	.settings(commonSettings)
lazy val day21 = (project in file("Day 21"))
	.settings(commonSettings)
lazy val day22 = (project in file("Day 22"))
	.settings(commonSettings)
lazy val day23 = (project in file("Day 23"))
	.settings(commonSettings)
lazy val day24 = (project in file("Day 24"))
	.settings(commonSettings)
lazy val day25 = (project in file("Day 25"))
	.settings(commonSettings)